AGENT_MESG_OUTPUT_DIMS = 1
AGENT_MESG_INPUT_DIMS = 1
MESSAGE_NOISE_STDDEV = 1.0
EXPLORE_PROB = 0.1
LEARNING_RATE = 0.0025
NO_AGENTS = 3
CORRECT_REWARDS = [1.0, 0.5, 0.25]
INCORRECT_REWARDS = [-1.0, -0.5, -0.25]

assert len(CORRECT_REWARDS) ==  len(INCORRECT_REWARDS) and len(INCORRECT_REWARDS) == NO_AGENTS, "Check Config Dims"